# Generated by Django 3.1.5 on 2021-01-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_cookies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cookies',
        ),
    ]
