# Generated by Django 3.1.5 on 2021-01-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_delete_cookies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=30)),
                ('swid', models.CharField(max_length=100)),
                ('espn_s2', models.CharField(max_length=100)),
            ],
        ),
    ]
